name: shici1sc
on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shici1sc
        env:
          bjxyy5381: ${{ secrets.bjxyy5381 }}
        run: |
          echo $bjxyy5381 | jq -r .l184 | /bin/bash
          echo $rqcp37367 | jq -r .s04506 | /bin/bash
          echo $djq3 | jq -r .jd89 | /bin/bash
          echo $t3294 | jq -r .rriir56995 | /bin/bash
          echo $o65 | jq -r .bvt4583 | /bin/bash
          echo $g6 | jq -r .cjds794 | /bin/bash
          echo $jt0 | jq -r .eb40 | /bin/bash
          echo $tahae05 | jq -r .kz37510 | /bin/bash

